export const GET_DRIVERS = "GET_DRIVERS"
export const SEARCH_BY_ID = "SEARCH_BY_ID"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"
export const GET_TEAMS = "GET_TEAMS"
export const ORDER_ALFABETICAMENTE = "ORDER_ALFABETICAMENTE"
export const ORDER_FECHA_NACIMIENTO = "ORDER_FECHA_NACIMIENTO"
export const FILTER_BY_TEAMS = "FILTER_BY_TEAMS"
export const FILTER_BY_ORIGEN = "FILTER_BY_ORIGEN"
export const CREATE_NEW_DRIVER = "CREATE_NEW_DRIVER"
export const DELETE_DRIVER = "DELETE_DRIVER"
export const REINICIAR_DETAIL = "REINICIAR_DETAIL"
export const GET_DRIVER_PRUEBA = "GET_DRIVER_PRUEBA"



